### ISSUE TITLE
Add Support/Fix for animationData from loadAnimation.

### ISSUE THREAD

**Issue by deve-sh** [LottieFiles/jlottie#25]
Currently `animationData` doesn't work with `loadAnimation`, it will be a great feature to have in the library.

https://github.com/LottieFiles/jlottie/blob/2333943feb234b030f2633746527d5377c12353c/src/jlottie.js#L3056

**IMP**: I noticed the above line in the codebase, and would just want to confirm that if `animationData` is passed as a JavaScript Object, the `length` attribute doesn't exist on it, hence changing it to `Object.keys(obj.animationData).length > 0` should work better.

**Comment by shaafiee** [comment]
I have pushed a fix that should now allow you to load animations via 'animationData'.

**Comment by Inc-Peter** [comment]
It seems this bug has been reintroduced:
https://github.com/LottieFiles/jlottie/blob/d030c002d2bc22e53c532e8583ef822de897dd33/src/jlottie.js#L3921
It would probably be easier for you to catch, if one of the examples used animationData.
