### ISSUE TITLE
loadAnimation method ignores `autoplay: false`, the animations always autoplay on load.

### ISSUE THREAD

**Issue by circa1983** [LottieFiles/jlottie#27]
Following your example code, I can’t seem to prevent the animations from autoplaying.
Stripped down example:
```
<script>
let lottieIcon = document.getElementById("my-animation");
jlottie.loadAnimation({
  container: lottieIcon,
  loop: false,
  autoplay: false, // Set to false but still autoplays, am I missing something?
  path: "https://assets6.lottiefiles.com/private_files/lf30_8walmmtg.json" });
</script>    
```
Functioning example of issue: https://codepen.io/samwalker/pen/0608d732e98db09451f355161c3460be?editors=1010
Output:  https://cdpn.io/samwalker/debug/0608d732e98db09451f355161c3460be

**Comment by shaafiee** [comment]
I have pushed an fix for this.

**Comment by circa1983** [comment]
Brilliant thank you @shaafiee and many thanks for providing such an awesome library!
