### ISSUE TITLE
Feature Request: dot.lottie format support

### ISSUE THREAD

**Issue by alolalo** [LottieFiles/jlottie#47]
Hi jLottie,

I really like the performance-side of this and wonder if you are going to support dot.lottie file-format, which does a great deal at compressing lottie-files up to 90%. That would make this version of lottie my goto version if I need only a subset of lottie.

**Comment by kyle-cognizant** [comment]
@shaafiee was this ever added? why did you close it as completed the same day that the feature request was created?
